apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streaming-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/haziqishere/minecraft-kubernetes
    targetRevision: HEAD
    path: kubernetes/streaming
  destination:
    server: https://kubernetes.default.svc
    namespace: streaming
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
