apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/haziqishere/minecraft-kubernetes
    targetRevision: HEAD
    path: minecraft
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true