apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "25565"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: minecraft
        image: haziqishere/minecraft-custom:main-18e0e02
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "PAPER"
        - name: VERSION
          value: "LATEST"
        - name: MEMORY
          value: "4G"
        - name: DIFFICULTY
          value: "hard"
        - name: MAX_PLAYERS
          value: "10"
        - name: MOTD
          value: "§6✦ §l§cKRONI SMP§r §6✦\\n§7Survival • Hard Mode • Paper 1.21"
        - name: ONLINE_MODE
          value: "true"
        - name: ENABLE_RCON
          value: "true"
        - name: RCON_PASSWORD
          value: "minecraft"
        - name: ICON
          value: "https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2F64x64-pixel-art-from-online-image-not-mine-v0-nv84yfxfwxoe1.png%3Fwidth%3D512%26format%3Dpng%26auto%3Dwebp%26s%3D0785af099a6068d91594e102a6f527673255733c"
        - name: OVERRIDE_ICON
          value: "TRUE"
        - name: SERVER_NAME
          value: "KroniSMP"
        ports:
        - containerPort: 25565
          name: minecraft
          protocol: TCP
        - containerPort: 25575
          name: rcon
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "6Gi"
            cpu: "2000m"
        livenessProbe:
          exec:
            command:
            - mc-health
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - mc-health
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-data